Add Air Pollution
freekode/pyopenweathermap pull request #18
Opened 2024-10-25 21:47 UTC by iomartin

I decided to implement the air pollution data that I asked on #17 as it was pretty straightforward to add.

I can start working on adding to HA once this gets merged

2024-10-28 08:09 UTC, freekode requested changes

2024-10-28 08:09 UTC, freekode commented on src/pyopenweathermap/client/free_client.py
> +        if api_type == 'current':
let's don't mix different clients together. air pollution client should be created in `owm_client_factory.py`

2024-10-28 08:09 UTC, freekode commented on src/pyopenweathermap/client/onecall_client.py
> +        self.air_pollution = OWMAirPollutionClient(api_key, self.http_client)
the same, shouldn't be here

2024-10-28 08:09 UTC, freekode commented on tests/test_all.py
> +    report = await client.get_air_pollution(LATITUDE, LONGITUDE)
tests are identical, it's better to extract it to separated method and remove duplicates. also by removing `current` and `forecast` only single test will remain

2024-10-29 20:53 UTC, iomartin commented
Thanks for the review @freekode, it will be a couple of days until I have some time to address your comments

2024-11-02 21:30 UTC, iomartin commented
@freekode I've updated this PR addressing your comments. I made air_pollution_client.py a subclass of OWMClient(). Let me know if you don't like raising NotImplementedError() if someone for example calls get_weather() for the air pollution api. I thought it would be better than returning None, which could give the impression that something went wrong but was valid usage nonetheless.

Alternatively, we could rename get_weather() into something more generic like get_data() and then each subclass would only need to implement one function

2024-11-06 16:05 UTC, freekode commented
LGTM Thanks
>if you don't like raising NotImplementedError()
Yeah, I think this is much better than return None.

>Alternatively, we could rename get_weather() into something more generic like get_data() and then each subclass would only need to implement one function
This is good idea. I even thought about to split it to get_current and get_forecast. So client can separate request for forecast.

2024-11-06 16:09 UTC, merged